package KieRule;
import com.javatechie.spring.drools.api.Order;
import com.javatechie.spring.drools.api.Priority;
global  com.javatechie.spring.drools.api.Order orderDiscount;

function String message(String cardType) {
    return "Discount applied for bank:" + cardType + "!";
}

rule "HDFC"
when
orderObject : Order(cardType=="HDFC" && price>10000);

then
orderObject.setDiscount(10);
System.out.println( message( "HDFC" ) );
end;

rule "ICICI"
when
orderObject : Order(cardType== "ICICI" && price>15000);
then
orderObject.setDiscount(8);
System.out.println( message( "ICICI" ) );
end;

rule "DBS"
when
orderObject : Order(cardType=="DBS" && price>15000);
then
orderObject.setDiscount(15);
end;